<?php

/**
 * This file was generated by DAMB
 *
 * @copyright   Copyright (c) 2019 - 2020, AXeL-dev
 * @license     GPL
 * @link        https://github.com/AXeL-dev/damb
 */

// Load Dolibarr environment (mandatory)
if (false === (@include_once '../../main.inc.php')) { // From htdocs directory
    require_once '../../../main.inc.php'; // From "custom" directory
}

// Load page & ${module_folder} lib
dol_include_once('${module_folder}/lib/page.lib.php');
dol_include_once('${module_folder}/lib/${module_folder}.lib.php');

// Control access to page
control_access('$user->admin');

/**
 * View
 */

print_header('Changelog', array('admin', '${lang_file}@${module_folder}'), array('{module_folder}/css/changelog.css'));

print_subtitle('Changelog', 'title_generic.png', 'link:modules_list');

print_admin_tabs('Changelog');

load_template('${module_folder}/tpl/changelog.tpl.php', array(
    'changelog_file' => dol_buildpath('${module_folder}/changelog.json')
));

print_footer(true);
