<?php

/**
 * This file was generated by DAMB
 *
 * @copyright   Copyright (c) 2019 - 2020, AXeL-dev
 * @license     GPL
 * @link        https://gitlab.com/AXeL-dev/damb
 */

// Load Dolibarr environment (mandatory)
if (false === (@include_once '../../main.inc.php')) { // From htdocs directory
    require_once '../../../main.inc.php'; // From "custom" directory
}

// Load page lib
dol_include_once('${module_folder}/lib/page.lib.php');

// Control access to page
control_access('$user->admin');

/**
 * View
 */

print_header('Changelog', array('admin', '${lang_file}@${module_folder}'), array('{module_folder}/css/changelog.css'));

print_subtitle('Changelog', 'title_generic.png', 'link:'.DOL_URL_ROOT.'/admin/modules.php?mainmenu=home:label:BackToModuleList');

$tabs = array(
    array('title' => 'Setup', 'url' => '${module_folder}/admin/setup.php?mainmenu=home'),
    ${more_tabs}array('title' => 'Changelog', 'url' => '${module_folder}/admin/changelog.php?mainmenu=home', 'active' => true),
    array('title' => 'About', 'url' => '${module_folder}/admin/about.php?mainmenu=home')
);
print_tabs($tabs, '${module_name}', '${module_picture}@${module_folder}', -1);

load_template('${module_folder}/tpl/changelog.tpl.php', array(
    'changelog_file' => dol_buildpath('${module_folder}/changelog.json')
));

print_footer(true);
