<?php

/**
 * This file was generated by DAMB
 *
 * @copyright   Copyright (c) 2019 - 2020, AXeL-dev
 * @license     GPL
 * @link        https://github.com/AXeL-dev/damb
 */

require_once DOL_DOCUMENT_ROOT . '/core/class/commondocgenerator.class.php';
require_once DOL_DOCUMENT_ROOT . '/core/lib/functions2.lib.php';

/**
 * Modele${doc_model_class_name} class
 */
abstract class Modele${doc_model_class_name} extends CommonDocGenerator
{
    /**
     * Return list of active generation models
     *
     * @param   DoliDB      $db                     Database handler
     * @param   integer     $maxfilenamelength      Max length of value to show
     * @return  array                               List of templates
     */
    public static function liste_modeles($db, $maxfilenamelength=0)
    {
        $list = getListOfModels($db, '${doc_model_type}', $maxfilenamelength);

        return $list;
    }
}

// FIX for Dolibarr >= 8
abstract class ModelePDF${doc_model_class_name} extends Modele${doc_model_class_name} {}
