<?php

/**
 * This file was generated by DAMB
 *
 * @copyright   Copyright (c) 2019 - 2020, AXeL-dev
 * @license     GPL
 * @link        https://github.com/AXeL-dev/damb
 */

// Load Dolibarr environment (mandatory)
if (false === (@include_once '${include_prefix}../main.inc.php')) { // From htdocs directory
    require_once '${include_prefix}../../main.inc.php'; // From "custom" directory
}

// Load page lib
dol_include_once('${module_folder}/lib/page.lib.php');

// Control access to page
//control_access('$user->admin');

// Load translations
load_langs(array('${lang_file}@${module_folder}'));

// Get parameters
$action = GETPOST('action', 'alpha');

/**
 * Actions
 */

if ($action == 'someaction')
{
    // Do something..
}

/**
 * View
 */

print_header('${page_title}');

print_subtitle('${page_title}', 'title_generic.png');

echo 'Add some content here..';

print_footer();
